# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        npm install
- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        npm install
        npm test
- stage: Deploy
  displayName: 'Deploy to Azure'
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureFunctionApp@2
      inputs:
        connectedServiceNameARM: 'Azure for Students(b96627c2-d823-46f0-b909-7fdba823b9bc)'
        appType: 'functionAppLinux'
        appName: 'myAzureFunctionApp'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto'